version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: "postgres_db"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "${DB_PORT}:5432"
    restart: always
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    env_file:
      - .env
    volumes:
      - data_pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
  app:
    build: .
    container_name: "python_app"
    depends_on:
      - db
    working_dir: /app
    command: ["./wait-for-postgres.sh", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5001"]
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    restart: always

volumes:
  postgres_data:
  data_pgadmin:
